### ISSUE TITLE
Should we ask people to improve their lighting?

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/eyedata#8]
Avoid backlight, clear view of eyes.

**Comment by j-e-man** [comment]
There's a screen where users can see what they look like through their webcam, along with these instructions: 

"Please adjust the camera, your position, and the lighting to get a good view of your face and especially your eyes."

Maybe just add below it:

"Tips: To avoid backlighting, make sure a strong light is in front of you. If you can clearly see the whites of your eyes, you're likely in a good spot."

**Comment by jodeleeuw** [comment]
That works for me. I like the "If you can clearly see..." piece especially. Gives the participant a clear goal.

**Comment by j-e-man** [comment]
Should I also add that the participant should be the only face in frame?

**Comment by jodeleeuw** [comment]
Yeah, can't hurt!
